Ignore mutation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,12 +40,12 @@ jobs:
           name: .repo.patch
           path: .repo.patch
           overwrite: true
-      - name: Fail build on mutation
-        if: steps.self_mutation.outputs.self_mutation_happened
-        run: |-
-          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
-          cat .repo.patch
-          exit 1
+      # - name: Fail build on mutation
+      #   if: steps.self_mutation.outputs.self_mutation_happened
+      #   run: |-
+      #     echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+      #     cat .repo.patch
+      #     exit 1
       - name: Backup artifact permissions
         run: cd dist && getfacl -R . > permissions-backup.acl
         continue-on-error: true
